version: "3"

services:
  mariadb:
    container_name: "scorm_db"
    image: "bitnami/mariadb:latest"
    environment:
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "mariadb_data:/bitnami"
    networks:
      - moodle

  moodle:
    container_name: "scorm_moodle"
    image: "bitnami/moodle:latest"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_USERNAME=adm
      - MOODLE_PASSWORD=adm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "moodle_data:/bitnami"
    depends_on:
      - mariadb
    networks:
      - moodle

volumes:
    mariadb_data:
    moodle_data:
networks:
    moodle:
      